### ISSUE TITLE
AUheader heading should be a h1

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/design-system-starter#152]
Nice pick up @MattFredBrooks.

The heading in the header should be a h1, since it's the top level heading.

![image](https://user-images.githubusercontent.com/20184809/61917076-b6e21f00-af8e-11e9-8983-318cf4479c49.png)

**Comment by AlokTakshak** [comment]
@sukhrajghuman I would like to take it

**Comment by sukhrajghuman** [comment]
@AlokTakshak sure 🙂

**Comment by AlokTakshak** [comment]
> @AlokTakshak sure 🙂

Done

**Comment by sukhrajghuman** [comment]
closed by #153
