### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by timcoxopc** [govau/design-system-starter#186]
In the root README.md file all the links under the **Templates** and **Development environment** headings are broken. They are trying to link to a github pages site that does not exist.

**Comment by KiriHoy** [comment]
Hi @timcoxopc Thanks for the pickup! 
The links for the Templates will be fixed as part of #187. I couldn't seem to find broken links under the Development environment heading, please feel free to clarify this one further if something has been missed.

**Comment by timcoxopc** [comment]
Thanks @KiriHoy. The links under the development heading are working fine for me now. Pretty sure they were down on Friday when I was looking, but I might of confused myself.

**Comment by KiriHoy** [comment]
All good @timcoxopc, Thanks!
